### ISSUE TITLE
Request: bind Formik `status`

### ISSUE THREAD

**Issue by joshlarsen** [turner-industries/formik-semantic-ui#9]
Is there a way to access Formik `status`? I see that `handleSubmit` and `isSubmitting` are bound automatically, but I don't see `status`.

> Automatically binds Formik` handleSubmit` for Semantic UI Form onSubmit
> Automatically binds Formik `isSubmitting` for Semantic UI Form loading

We've been using `status` for feedback messages after server-side validation. Any pointers? Thanks.

**Comment by justinobney** [comment]
@joshlarsen Something like this?
https://codesandbox.io/s/62r0764ywz

**Comment by justinobney** [comment]
This library was born out of a project at work where we only use server-side validation. I have since updated it to attempt to work with both client and server-side validation. I did not think about using `status` for "connecting" the server-side errors and leaving the built-in formik error handling alone. But I might re-evaluate that and see where I can get using status.

**Comment by joshlarsen** [comment]
@justinobney no, this is perfect. We are also using only server-side validation. It was my mistake, I wasn't passing `status` in an object. Works great now, thanks.
